### ISSUE TITLE
Linux suspends during a heavy enclave processing

### ISSUE THREAD

**Issue by kunisuzaki** [keystone-enclave/keystone#112]
[test.patch.txt](https://github.com/keystone-enclave/keystone/files/3548923/test.patch.txt)

This article moves from the forum.

I found a heavy enclave processing suspend the Linux on SiFive Unleashed board.
After the heavy enclave processing, the Linux reactivates.
Is it correct behavior?

I attach a git-patch to create a heavy enclave processing in the keystone-demo.
https://github.com/keystone-enclave/keystone-demo

Please take care of the reproduction. My Linux may break the file system.
I can not boot the Linux now.

When the word counting runs in the enclave, the Linux behavior is suspended about 2 minutes.

The Linux suspension is clear when the first word counting. It stops the "top" command.
However,  the "top" command can run during the second word counting.
What did it happen?

**Comment by dayeol** [comment]
Seems very familiar issue to me.
I'll take a look into the issue and get back shortly.

**Comment by dayeol** [comment]
It turns out that there's a timer interrupt bug. 
The enclave is not timer-interrupted in some cases and I'm further investigating the cause.

**Comment by kunisuzaki** [comment]
Thank you for your investigation, Dayeol.
Is it a hardware ”HiFive unleased board” bug or a runtime "Eyrie" bug?

**Comment by dayeol** [comment]
it is Eyrie bug.

**Comment by dayeol** [comment]
In fact, it is more than that. We haven't yet implemented the DoS protection against enclaves. Please refer to the following issue : https://github.com/keystone-enclave/keystone/issues/46.

**Comment by dayeol** [comment]
I finally have got the fix for this issue.
We'll be releasing the updated version shortly.

**Comment by dayeol** [comment]
This issue has been moved to #113. Closing

**Comment by dayeol** [comment]
@kunisuzaki  To follow up, this has been resolved in `dev` branch.
Try to fetch the branch.
Make sure to update the submodules as well (`git submodule update --recursive`).

**Comment by kunisuzaki** [comment]
Thank you Dayeol.
I confirmed the Linux works well along with heavy keystone processing.
However, I still have a question because the workload on Linux does not show the keystone processing. 
While I monitor each core's workload with "htop", the "htop" does not show any busy cores.
Doesn't the Linux monitor the load on keystone because of Logical Partition?

When I monitored the load on OP-TEE on ARM TrustZone, the Linux monitoring tool showed the Linux kernel consumes a core.

**Comment by dayeol** [comment]
@kunisuzaki I have opened a new issue for this.
My guess is that the enclave is scheduled from the security monitor, which is not tracked by the Linux kernel. To fix this issue, one should understand how performance/load monitoring works in Linux, and modify the driver such that the linux is aware of time spent inside the enclave.
